spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://shahir-db.c3mac8u4807a.ap-southeast-5.rds.amazonaws.com:5432/testDB
    username: postgres
    password: shahirdb
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080